# Generated by Django 3.2.6 on 2022-03-27 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employeedb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=100)),
                ('employee_email', models.EmailField(max_length=254)),
                ('employee_age', models.IntegerField()),
                ('employee_image', models.ImageField(upload_to='employee_image')),
            ],
        ),
    ]
