# Generated by Django 3.2.6 on 2022-04-06 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUDAPP', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeedb',
            name='employee_age',
        ),
        migrations.RemoveField(
            model_name='employeedb',
            name='employee_email',
        ),
        migrations.RemoveField(
            model_name='employeedb',
            name='employee_image',
        ),
        migrations.RemoveField(
            model_name='employeedb',
            name='employee_name',
        ),
        migrations.AddField(
            model_name='employeedb',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='employeedb',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='employeedb',
            name='place',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='employeedb',
            name='upload_image',
            field=models.ImageField(blank=True, upload_to='emp_image'),
        ),
    ]
