# Generated by Django 3.2.6 on 2022-04-11 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUDAPP', '0002_auto_20220407_0337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedb',
            name='upload_image',
            field=models.FileField(blank=True, upload_to='emp_image'),
        ),
    ]
